language: node_js
node_js:
  - 12.13.0
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: ${{githubTokenBis}}
  on:
    branch: master

install:
    - npm ci

script:
    - npm run test-travis

after_success:
    - npm run coveralls

notifications:
  - email: false
