language: node_js
node_js:
  - 12.13.0

services:
    - mongodb

before_script:
    - sleep 15
    - mongo mydb_test --eval 'db.createUser({user:"travis", pwd:"password", roles:["readWrite"]});'

install:
    - npm ci

script:
    - npm run test-travis

after_success:
    - npm run coveralls

notifications:
  - email: false
