language: node_js
node_js:
    - 12.13.0

services:
    - mongodb

env:
    - TRAVIS=1

install:
    - npm ci

script:
    - npm run test-travis

after_success:
    - npm run coveralls

notifications:
    - email: false
