version: '3'

services:
    web:
        build: ./
        ports:
            - "${WEB_PORT}:${WEB_PORT}"
        links:
            - "mongodb:${DB_HOST}"
        volumes:
            - "./src:/code/src"

    mongodb:
        image: "mongo:${DB_TAG}"
        ports:
            - "${DB_PORT}:${DB_PORT}"
