version: '3'

services:
    web:
        build: ./
        ports:
            - "${DB_PORT}:${DB_PORT}"
        links:
            - "mongodb:${DB_HOST}"
    mongodb:
        image: "mongo:${DB_TAG}"
