version: '3'

services:
    web:
        build: ./
        ports:
            - "${WEB_PORT}:${WEB_PORT}"
        links:
            - "mongodb:${DB_HOST}"

    mongodb:
        image: "mongo:${DB_TAG}"
