version: '3'

services:
    web:
        build: ./
        ports:
            - "${WEB_PORT}:${WEB_PORT}"
        links:
            - "mongodb:${DB_HOST}"
        volumes:
            - "./src:/code/src"
            - "./test:/code/test"
            - "./.env:/code/.env"
        container_name: web
        environment:
            - APP_ENV=${APP_ENV}

    mongodb:
        image: "mongo:${DB_TAG}"
        container_name: mongodb
